apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n5be
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-n5be@sha256:fe4366b7f9c723082c2cf0e70135b6e747a05b2e0135c8e9c38098f1ba9614e7
        name: my-nodejs
        resources: {}
status: {}
